version: '3.8'

services:
  mailsysem:
    build: .
    container_name: mailsysem_app
    restart: always
    ports:
      - "3005:3000" # Expose on port 3005 to avoid conflict with existing apps
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=https://mail.ro9.in
      - AUTH_TRUST_HOST=true
      - REDIS_URL=redis://redis:6379
    networks:
      - mailsysem_net
      - crux-invoice-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: mailsysem_redis
    restart: always
    networks:
      - mailsysem_net

networks:
  mailsysem_net:
    driver: bridge
  crux-invoice-network:
    external: true
